### ISSUE TITLE
Sonderzeichen in Titeln erlauben

### ISSUE THREAD

**Issue by jakobwes** [serlo-org/athene2-rfcs#28]
Sonderzeichen, oder andere Sprachzeichen sind im Moment noch nicht in Titeln von Serlo-Artikeln, -Kursen,... erlaubt. Das wäre wichtig das zu ändern (wenn das möglich ist).
Auch ist das linked mit issue #27 da das ermöglichen wird neue Sprachversionen von Serlo während der tenant aufgesetzt wird, erstmal im Sandkasten von en.serlo.org zu entwickeln und dann, wenn der tenant steht, einfach rüber zu kopieren (sei es technisch oder manuell)

**Comment by inyono** [comment]
Sonderzeichen sind WIP: https://github.com/serlo/athene2/pull/795, kann das aber nochmal ansprechen und ggf. höher priorisieren

**Comment by jakobwes** [comment]
Guter Hinweis. Das habe ich nicht gesehen. Danke! Also wenn das ginge, wäre das super :)

**Comment by Knorrke** [comment]
Should be fixed now in https://github.com/serlo/serlo.org/pull/11. Please create an issue in that repo, if there's still problems with this.
