### ISSUE TITLE
User Profile standardisieren

### ISSUE THREAD

**Issue by kulla** [serlo-org/athene2-rfcs#45]
Macht es Sinn, dass wir für dieses Jahr noch auf die Roadmap nehmen, die Angaben auf den User Profilen zu standardisieren? Ich stelle mir vor, dass es ein paar wenige optionale Standardfelder gibt. z.B:

* Profilbild
* Über mich
* Warum mache ich bei Serlo Education mit?
* ein großes Freifeld, das mit dem Editor bearbeitet werden kann.

**Comment by inyono** [comment]
IMHO: only if needed for the Crowd-bird stuff.

**Comment by kulla** [comment]
Issue can be closed since we have https://github.com/serlo/serlo.org/issues/402 as a duplicate issue in the community upgrade project.
