### ISSUE TITLE
Simplify exercise editing

### ISSUE THREAD

**Issue by elbotho** [serlo-org/athene2-rfcs#62]
**Discussion with Wolfgang und David:**

- always open complete exercise collections in editor
- (only have one edit link)

**Thinks to consider/change:**
- maybe offer the option to fold/unfold subexercises in the editor
- how to we merge the activity log etc?
- does the new diff view work well enough to handle collections with long answers or many subexercises?

**Comment by CarolinJaser** [comment]
Moved to Google Doc https://docs.google.com/document/d/1rSkFo2JtsSwHHsbosQcgAN4EzeePXLnqi_eCFpUM3u4/edit#
